---
title: "BarChart-Debris"
author: "Brie Sherow"
date: "04/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries, echo=FALSE, include=FALSE}
lib.load = c("here", "ggplot2", "dplyr", "lubridate", "forcats", "ggthemes", "knitr", "kableExtra") 
lapply(lib.load, require, character.only = TRUE) 

```

```{r load-data}
data <- read.csv(file="data/all_data.csv", header=T, sep=",")
data$Date <- dmy(data$Date)
data$Notes <- as.character(data$Notes)

site_select <- data %>%
  filter(Team=="UNSW" & Location %in% c("DOUBL","WATSO","PARSL","NEUTR","CLIFT")) %>%
  select(-Habitat2, -Fragment, -Whole)
```

```{r load-item-code}
item_code <- read.csv(file="data/CSIRO-code.csv", header=T, sep=",") #load item names
item_code <- item_code %>%
  select(ID, item_name) #filter out material as some item types may have more than one material type (ex. fishing items, furniture)
```

```{r survey-count}
#create a count for number of surveys
sampling_dates <- data %>%
  group_by(Location) %>%
  filter(Team=="UNSW") %>%
  count(Date)

#take away the debris count
sampling_dates$n <- NULL

sampling_dates <- sampling_dates %>%
  count(Location) %>%
  arrange(desc(n)) %>%
  rename(NumberSurveys=n)

#join survey to site select
site_select <- left_join(site_select, sampling_dates, by="Location")
```


```{r item-counts}
#normalise sites
site_total_item <- site_select %>%
  group_by(Site, Material, ID) %>%
  mutate(mean=sum(Total)/NumberSurveys, #mean of item type per site
         mean_sd=sd(Total)) %>% #sd of item type per site
        ungroup()

site_total_item <- site_total_item %>%
  select(Location, Habitat, Site, Material, ID, mean, mean_sd) %>%
  filter(mean > 0) %>%
  distinct()
  
site_total_item <- left_join(site_total_item, item_code, by="ID")

top_items_per_site <- site_total_item %>% group_by(Site) %>% top_n(2, mean)
```


```{r top-items}
item_total <- site_select %>%
  group_by(Material, ID) %>%
  mutate(sum=sum(Total), #sum of total items by type
         sd=sd(Total)) %>% #sd of total items by type
        select(ID, Material, sum, sd) %>% #remove irrelevant columns
        filter(sum>0) %>% #remove null values
        arrange(desc(sum)) %>% #show high counts first
        distinct() %>% #remove duplicate entries
        ungroup()

item_total <- left_join(item_total, item_code, by="ID") #join item names

top_items <- item_total %>% top_n(20, sum) #show top 20 items over all surveys combined

rmarkdown::paged_table(top_items) %>% #print clean table
kable("html", col.names = c("ID", "Material", "Sum", "SD", "Name"),
      caption = "Top 20 items across all surveys") %>% 
  kable_styling(bootstrap_options="condensed", position="left") %>%
  scroll_box(width = "100%", height = "500px")
``` 

```{r material-counts}
#normalise sites
site_total_mat <- site_select %>%
  group_by(Site, Material) %>%  #group by material findings at each site
  summarise(mean=mean(Total), #mean of item type per site
         mean_sd=sd(Total)) %>% #sd of item type per site
        ungroup()

# plyr version of the same thing:
# site_total_mat <- plyr::ddply(site_select,
#                         .(Site, Material), # group by these factors
#                         summarise,
#                         mean=mean(Total),
#                         sd=sd(Total)
#                         )


site_total_mat <- site_total_mat %>%
  filter(mean > 0) %>% #remove 0 values
  distinct() #remove duplicates

# rename material categories 
var_change <- c("Ceramic", "Undetermined", "E-Waste", "Paper", "Construction", "Organic", "Unknown", "Timber", "Foam", "Brick or Cement", "Rubber", "Cloth", "") #state variables to rename
site_total_mat$Material <- as.character(site_total_mat$Material) #change Material to character
site_total_mat$Material[site_total_mat$Material %in% var_change] = "Other" #set categories to Other

#top materials at each site by mean
top_mat_per_site <- site_total_mat %>% group_by(Site) %>% top_n(1, mean)

rmarkdown::paged_table(top_mat_per_site) %>% #print clean table
kable("html", col.names = c("Site", "Material", "Mean", "SD"),
      caption = "Top Material Type per Site") %>% 
  kable_styling(bootstrap_options="condensed", position="left") %>%
  scroll_box(width = "100%", height = "500px")
``` 
        
```{r pier-items}
P <- site_select %>%
  filter(Habitat=="P") #isolate pier sites

total_P <- P %>%
  group_by(Site, Material, ID) %>% #looking at item types per site
  summarise(item_total=sum(Total), #total number of each item per site
            mean=item_total/unique(NumberSurveys)) %>% #mean of each item per site
  arrange(desc(mean)) #listed by largest means

total_P <- left_join(total_P, item_code, by="ID") #adding item name

P_map <- total_P %>% #create csv to use for spatial map
  group_by(Site) %>%
  summarise(mean_items=sum(mean))
  
  write.csv(P_map, "output/P_mapping.csv", row.names = FALSE) #save this data frame as a csv file

# total_P <- total_P %>%
#   filter(mean>0) #filter out zero values

total_P$Material <- as.character(total_P$Material) #change Material to character
total_P$Material[total_P$Material %in% var_change] = "Other" #set categories to Other

p_total_P <- total_P %>%
  mutate(item_name=fct_reorder(item_name,desc(mean))) %>%
  ggplot( aes(x=Material, y=mean, fill=Material)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~Site)

p_total_P

# ggsave(filename = "figures/total_p.png", plot = p_total_P, dpi = 600)
```


```{r sediment-items}
SS <- site_select %>%
  filter(Habitat=="SS")

total_SS <- SS %>%
  group_by(Site, Material, ID) %>% #looking at item types per site
  summarise(item_total=sum(Total), #total number of each item per site
            mean=item_total/unique(NumberSurveys)) %>% #mean of each item per site
  arrange(desc(mean)) #listed by largest means

total_SS <- left_join(total_SS, item_code, by="ID") #adding item name

SS_map <- total_SS %>% #create csv to use for spatial map
  group_by(Site) %>%
  summarise(mean_items=sum(mean))
  
  write.csv(SS_map, "output/SS_map.csv", row.names = FALSE) #save this data frame as a csv file

# total_SS <- total_SS %>%
#   filter(mean>0) #filter out zero values

total_SS$Material <- as.character(total_SS$Material) #change Material to character
total_SS$Material[total_SS$Material %in% var_change] = "Other" #set categories to Other

p_total_SS <- total_SS %>%
  mutate(item_name=fct_reorder(item_name,desc(mean))) %>% 
  ggplot( aes(x=Material, y=mean, fill=Material)) +
  geom_col() +
  coord_flip() + 
  facet_wrap(~Site)

p_total_SS

# ggsave(filename = "figures/total_ss.png", plot = p_total_SS, dpi = 600)
```
```{r fishing}
fishing <- site_select %>%
  group_by(Site, Fishing) %>% #group by fishing or non-fishing
  summarise(item_total=sum(Total), #total fishing items
            mean=item_total/unique(NumberSurveys)) %>% #total per survey
  arrange(desc(mean))

site_habitat <- site_select %>%
  select(Site, Habitat, Location) %>%
  distinct() #create df for labeling

fishing <- left_join(fishing, site_habitat, by="Site") #join for labeling

write.csv(fishing, "output/fishing_map.csv", row.names = FALSE) #save this data frame as a csv file

p_fishing <- fishing %>%
  ggplot( aes(x=Habitat, y=mean, fill=Fishing)) +
  geom_bar(position="stack", stat="identity") +
  facet_wrap(~Location)

p_fishing

ggsave(filename = "figures/fishing.png", plot = p_fishing, dpi = 600)
```


```{r habitat}

habitat <- site_select 
habitat$Material <- as.character(habitat$Material) #change Material to character
habitat$Material[habitat$Material %in% var_change] = "Other" #set categories to Other

habitat <- habitat %>%
  group_by(Location, Habitat, Material) %>%
  summarise(item_total=sum(Total), #total number of each material type per site
            mean=item_total/unique(NumberSurveys), #mean of each material type per site
            mean_sd=sd(Total)) %>% #sd of each material type per site
  arrange(desc(mean))

write.csv(habitat, "output/habitat_map.csv", row.names = FALSE) #save this data frame as a csv file

# habitat <- habitat %>%
#   filter(mean>0) %>% #filter null values

p_habitat <- habitat %>%
  ggplot( aes(x=Habitat, y=mean, fill=Material)) +
  geom_bar(position="stack", stat="identity") +
  ggtitle("Mean of debris items per survey") +
  facet_wrap(~Location)
p_habitat

ggsave(filename = "figures/habitat.png", plot = p_habitat, dpi = 600)
```


```{r debris-through-time}
site_select_sum <- site_select %>%
  group_by(Date, Location, Habitat) %>%
  summarise(sum=sum(Total), mean=mean(Total), sd=sd(Total))

    
time_line <- ggplot(site_select_sum, aes(x=Date, y=sum, group=Habitat, colour=Habitat)) +
      geom_line() +
      geom_point() +
      ggtitle("Debris count per Survey") +
      guides(colour=guide_legend("Item type")) +
      ylab("Total item count") +
      facet_wrap(~Location)
    time_line
    
    ggsave(filename = "figures/timeline.png", plot = time_line, dpi = 600)
```

