---
title: "stats-tests"
author: "Brie Sherow"
date: "17/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries, warning=FALSE, message=FALSE, results='hide'}
library(ggplot2) #graphing
library(ggthemes) #graphing templates
library(hrbrthemes) #graphing templates
library(lubridate) #date manipulation
library(forcats) #working with factors
library(tidyverse) #manipulating data
library(knitr) #rmarkdown functions
#library(kableExtra) #table layouts
library(magick) #image processing
library(stats) #R stats functions
library(broom) #create summaries from stats objects
library(car) #lm regression
library(MASS) #stats
library(lme4) #glmer function
library(DHARMa) #testing model diagnostics
library(glmmTMB) #fit zero-inflated negative binomial
library(emmeans) #pairwise comparisons
```

# Site selection
10 sites at 5 locations were surveyed between 3-5 times each during summer 2019-2020.
```{r create-site-select}
#Site selection

  #read in processed survey data
  data <- read.csv(file="data/all_data.csv", 
                   header=T, sep=",", 
                   fileEncoding="UTF-8-BOM") #removes special characters
  
  data$Date <- dmy(data$Date) 
  data$Notes <- as.character(data$Notes)
  
  #keep only unsw surveys and sites with public piers and >2 survey rounds
  site_select <- data %>%
    filter(Team=="UNSW" & 
             Location %in% c("DOUBL","WATSO","PARSL","NEUTR","CLIFT")) %>%
    dplyr::select(-Habitat2, -Fragment, -Whole)
  
  #create a df for survey count per site
  sampling_dates <- data %>%
    group_by(Location) %>%
    filter(Team=="UNSW") %>%
    count(Date)
  
  #take away n
  sampling_dates$n <- NULL
  
  #create a column for survey count per site
  sampling_dates <- sampling_dates %>%
    count(Location) %>%
    arrange(desc(n)) %>%
    rename(NumberSurveys=n)
  
  #join survey count to site select
  site_select <- left_join(site_select, sampling_dates, by="Location")
  
  site_select <- site_select %>%
    mutate(survey_event = paste(Date, Site,sep=" "))

#Debris types
  
  #load item names
  item_code <- read.csv(file="data/CSIRO-code.csv", 
                        header=T, sep=",",
                         fileEncoding="UTF-8-BOM") #removes special characters
  
  #filter out material as some item types may have more than one material type 
  #(ex. fishing items, furniture)
  item_code <- item_code %>%
    dplyr::select(ID, item_name, Material, Dispersiveness, Fishing, Label) 
  
  site_select <- left_join(site_select, item_code, by="ID", suffix=c("", ".code"))
  
  site_select <- site_select %>%
    mutate(item = paste(Material, item_name, sep=": "))

#Site attributes
  
  #load site coords and distance from harbour mouth
  site_attr <- read.csv(file="data/site_attributes.csv", header=T, sep=",", fileEncoding="UTF-8-BOM")
  
  #add distance to harbour mouth to site_select data
  site_attr <- site_attr %>%
    dplyr::select(Site, CostDis, Coast) %>% #select only distance to harbour mouth for join
    mutate(DistKm = CostDis/100) #distance to harbour mouth
    
  #join distance to mouth to main dataset
  site_select <- left_join(site_select, site_attr, by="Site") 
```

## total

```{r drop1-total}
# Total interaction  0.051
  mod <- site_select %>%
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))
 
 #create model
  m_tot  <- glmmTMB(Total ~ #Debris count
                 Habitat * DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod)
 
drop1_tot <- drop1(m_tot, test="Chisq")

drop1_tot
```
```{r model-verification-total}

#create df to use for models
 mod <- site_select %>%
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))

#create model
  m_tot  <- glmmTMB(Total ~ #Debris count
                 Habitat * DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod)

so_tot <- simulateResiduals(fittedModel = m_tot, plot=T)
  
plotResiduals(so_tot)

testUniformity(so_tot) #tests if the overall distribution conforms to expectations
testOutliers(so_tot) #tests if there are more simulation outliers than expected
testDispersion(so_tot) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_tot) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_tot) #tests if there are more zeros than expected
```
```{r testing-temporal-autocorrelation, warning=FALSE, message=FALSE, results="hide"}
#creating a column from the model residuals
mod$resid = resid(m_tot) #create a column for each survey event's residuals

#Clifton Gardens - DW = 3.301, p-value = 0.05987
  m_clift <- mod %>%
    filter(Location=="CLIFT") %>% 
    group_by(Date) %>%
    summarise(sum=sum(resid))
  
  testTemporalAutocorrelation(m_clift$sum, 
                              time =  m_clift$Date) #test resid for temporal autocorrelation

#Double Bay - DW = 2.2347, p-value = 0.8496
  m_doubl <- mod %>%
    filter(Location=="DOUBL") %>%
    group_by(Date) %>%
    summarise(sum=sum(resid))
  
  testTemporalAutocorrelation(m_doubl$sum, 
                              time =  m_doubl$Date) #test resid for temporal autocorrelation

#Neutral Bay - DW = 2.767, p-value = 0.3581
  m_neutr <- mod %>%
    filter(Location=="NEUTR") %>%
    group_by(Date) %>%
    summarise(sum=sum(resid))
  
  testTemporalAutocorrelation(m_neutr$sum, 
                              time =  m_neutr$Date) #test resid for temporal autocorrelation
#Parsley Bay - DW = 1.2492, p-value = 0.4578
    m_parsl <- mod %>%
    filter(Location=="PARSL") %>%
    group_by(Date) %>%
    summarise(sum=sum(resid))
  
  testTemporalAutocorrelation(m_parsl$sum, 
                              time =  m_parsl$Date) #test resid for temporal autocorrelation
#Watsons Bay - DW = 2.8324, p-value = 0.3741
    m_watso <- mod %>%
    filter(Location=="WATSO") %>%
    group_by(Date) %>%
    summarise(sum=sum(resid))
  
  testTemporalAutocorrelation(m_watso$sum, 
                              time =  m_watso$Date) #test resid for temporal autocorrelation
```

```{r emmeans-total}
# Total
      em_tot_hd <- emmeans(m_tot, pairwise~ Habitat|DistKm , at=list(DistKm=c(1,8)), type="response", level=0.95, infer=T)
      em_tot_dh <- emmeans(m_tot, pairwise~ DistKm|Habitat , at=list(DistKm=c(1,8)), type="response", level=0.95, infer=T)
      
      em_tot1 <- summary(em_tot_hd$contrasts)
      em_tot1$Trait = "Total"
      
      em_tot2 <- summary(em_tot_dh$contrasts)
      em_tot2$Trait = "Total"
      
      em_tot1
      em_tot2
```

## items

```{r drop-levels-item}
options(scipen = 999)

top5 <- site_select %>%
  group_by(Label) %>%
  summarise(sum=sum(Total)) %>%
  arrange(desc(sum)) %>%
  top_n(5, sum)

#create vector from top 5 items
top5 <- top5$Label
top5 <- unlist(top5)

#All top + items of interest
top_txt <- site_select %>%
  filter(Label %in% top5) %>%
  mutate(Label = as.factor(Label)) %>%
  distinct(Label)%>%
  pull(Label) %>% 
  droplevels()

drop1_interaction = purrr::map_df(top_txt, function(x){
  
  temp_df <- site_select %>%
  filter(Label == paste0(x)) %>%
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat),
         Label = x)
 
 #create model
  m_temp  <- glmmTMB(Total ~ #Debris count
                 Habitat * DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = temp_df)
 
d <- drop1(m_temp, test="Chisq")
d$Label = x
return(d)
 })

drop1_interaction <- drop1_interaction %>%
  filter(LRT != "NA") %>%
  rename(p.value = 'Pr(>Chi)')

drop1_main = purrr::map_df(top_txt, function(x){
  
  temp_df <- site_select %>%
  filter(Label == paste0(x)) %>%
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat),
         Label = x)
 
 #create model
  m_temp  <- glmmTMB(Total ~ #Debris count
                 Habitat + DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = temp_df)
 
d <- drop1(m_temp, test="Chisq")
d$Label = x
return(d)
 })

drop1_main <- drop1_main %>%
  filter(LRT != "NA") %>%
  rename(p.value = 'Pr(>Chi)')

drop1_items <- rbind(drop1_interaction, drop1_main)
write.csv(drop1_items,"drop1_items.csv", row.names = T)
```

```{r model-verification-line}

#create df to use for models
mod_line <- site_select %>%
  filter(Label=="Fishing line") %>% #fishing line
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
              mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))

#GLM negative binomial with two variables
m_line  <- glmmTMB(Total ~ #Debris count
                 Habitat + DistKm + #predicted by distance from harbour mouth
                 (1|Location) + (1|Date), #site random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_line) 

so_line <- simulateResiduals(fittedModel = m_line, plot=T)
  
plotResiduals(so_line)

testUniformity(so_line) #tests if the overall distribution conforms to expectations
testOutliers(so_line) #tests if there are more simulation outliers than expected
testDispersion(so_line) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_line) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_line) #tests if there are more zeros than expected
```

```{r model-verification-glbtl}

#create df to use for models
mod_glbtl <- site_select %>%
  filter(Label=="Glass beverage bottle") %>% #fishing glbtl
  group_by(Date, Location, Habitat) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
              mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))

#GLM negative binomial with two variables
m_glbtl  <- glmmTMB(Total ~ #Debris count
                 Habitat + #predicted by distance from harbour mouth
                 (1|Location) + (1|Date), #site random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_glbtl) 

so_glbtl <- simulateResiduals(fittedModel = m_glbtl, plot=T)
  
plotResiduals(so_glbtl)

testUniformity(so_glbtl) #tests if the overall distribution conforms to expectations
testOutliers(so_glbtl) #tests if there are more simulation outliers than expected
testDispersion(so_glbtl) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_glbtl) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_glbtl) #tests if there are more zeros than expected
```

```{r model-verification-metsc}

#create df to use for models
mod_metsc <- site_select %>%
  filter(Label=="Metal scraps") %>% # metsc
  group_by(Date, Location, Habitat) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
              mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))

#GLM negative binomial with two variables
m_metsc  <- glmmTMB(Total ~ #Debris count
                 Habitat + #predicted by distance from harbour mouth
                 (1|Location) + (1|Date), #site random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_metsc) 

so_metsc <- simulateResiduals(fittedModel = m_metsc, plot=T)
  
plotResiduals(so_metsc)

testUniformity(so_metsc) #tests if the overall distribution conforms to expectations
testOutliers(so_metsc) #tests if there are more simulation outliers than expected
testDispersion(so_metsc) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_metsc) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_metsc) #tests if there are more zeros than expected
```

```{r model-verification-hooks}

#create df to use for models
mod_hook <- site_select %>%
  filter(Label=="Fishhook/sinker") %>% # hook
  group_by(Date, Location, Habitat) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
              mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))

#GLM negative binomial with two variables
m_hook  <- glmmTMB(Total ~ #Debris count
                 Habitat + #predicted by distance from harbour mouth
                 (1|Location) + (1|Date), #site random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_hook) 

so_hook <- simulateResiduals(fittedModel = m_hook, plot=T)
  
plotResiduals(so_hook)

testUniformity(so_hook) #tests if the overall distribution conforms to expectations
testOutliers(so_hook) #tests if there are more simulation outliers than expected
testDispersion(so_hook) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_hook) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_hook) #tests if there are more zeros than expected
```
```{r model-verification-misc-fish}

#create df to use for models
mod_fmisc <- site_select %>%
  filter(Label=="Fishing misc.") %>% # fmisc
  group_by(Date, Location, Habitat) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
              mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))

#GLM negative binomial with two variables
m_fmisc  <- glmmTMB(Total ~ #Debris count
                 Habitat + #predicted by distance from harbour mouth
                 (1|Location) + (1|Date), #site random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_fmisc) 

so_fmisc <- simulateResiduals(fittedModel = m_fmisc, plot=T)
  
plotResiduals(so_fmisc)

testUniformity(so_fmisc) #tests if the overall distribution conforms to expectations
testOutliers(so_fmisc) #tests if there are more simulation outliers than expected
testDispersion(so_fmisc) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_fmisc) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_fmisc) #tests if there are more zeros than expected
```
## material type

```{r drop-levels-material}
options(scipen = 999)

# Plastics interaction  (significant)
  plas_df <- site_select %>%
  filter(Material == "Plastic") %>%
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))
 
 #create model
  m_plas  <- glmmTMB(Total ~ #Debris count
                 Habitat * DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = plas_df)
 
drop1_plas_int <- drop1(m_plas, test="Chisq")

drop1_plas_int<- drop1_plas_int %>%
  filter(LRT != "NA") %>%
  rename(p.value = 'Pr(>Chi)') %>%
  mutate(Model = "Interaction",
         Material = "Plastic")

# Metals interaction  (not significant)
  met_df <- site_select %>%
  filter(Material == "Metal") %>%
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))
 
 #create model
  m_met  <- glmmTMB(Total ~ #Debris count
                 Habitat * DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = met_df)
 
drop1_met_int <- drop1(m_met, test="Chisq")

drop1_met_int<- drop1_met_int %>%
  filter(LRT != "NA") %>%
  rename(p.value = 'Pr(>Chi)') %>%
  mutate(Model = "Interaction",
         Material = "Metal")

# Metals main (Habitat significant)
  met_df <- site_select %>%
  filter(Material == "Metal") %>%
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))
 
 #create model
  m_met  <- glmmTMB(Total ~ #Debris count
                 Habitat + DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = met_df)
 
drop1_met_main <- drop1(m_met, test="Chisq")

drop1_met_main<- drop1_met_main %>%
  filter(LRT != "NA") %>%
  rename(p.value = 'Pr(>Chi)') %>%
  mutate(Model = "Main",
         Material = "Metal")

control=glmmTMBControl(optimizer=optim, optArgs=list(method="BFGS"))

# Glass interaction (significant)
  gls_df <- site_select %>%
  filter(Material == "Glass") %>%
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))
 
 #create model
  m_gls  <- glmmTMB(Total ~ #Debris count
                 Habitat * DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #date random effect
               family=nbinom2(), #negative binomial to deal with count data and zeros
               data = gls_df)
 
drop1_gls_int <- drop1(m_gls, test="Chisq")

drop1_gls_int<- drop1_gls_int %>%
  filter(LRT != "NA") %>%
  rename(p.value = 'Pr(>Chi)') %>%
  mutate(Model = "Interaction",
         Material = "Glass")

drop1_mat <- rbind(drop1_gls_int, drop1_met_main, drop1_met_int, drop1_plas_int)
write.csv(drop1_mat,"drop1_mat.csv", row.names = T)

```


```{r model-verification-mat-glass-int}
#create df of all glass
mod_gls <- site_select %>%
  filter(Material=="Glass") %>% #glass
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))


m_gls  <- glmmTMB(Total ~ #Debris count
                 Habitat*DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #site/date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_gls)

so_gls <- simulateResiduals(fittedModel = m_gls, plot=T)
  
plotResiduals(so_gls)

testUniformity(so_gls) #tests if the overall distribution conforms to expectations
testOutliers(so_gls) #tests if there are more simulation outliers than expected
testDispersion(so_gls) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_gls) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_gls) #tests if there are more zeros than expected
```
```{r model-verification-mat-glass-main}
# #create df of all glass
# mod_gls <- site_select %>%
#   filter(Material=="Glass") %>% #glass
#   group_by(Date, Location, Habitat) %>% #relevant variables
#   summarise(Total=sum(Total)) %>%
#   ungroup() %>%
#   mutate(Location = as.factor(Location),
#          Habitat = as.factor(Habitat))
# 
# 
# m_gls  <- glmmTMB(Total ~ #Debris count
#                  Habitat + #predicted by Habitat
#                  (1|Location) + (1|Date), #site/date random effect
#                family=nbinom1(), #negative binomial to deal with count data and zeros
#                data = mod_gls)
# 
# so_gls <- simulateResiduals(fittedModel = m_gls, plot=T)
#   
# plotResiduals(so_gls)
# 
# testUniformity(so_gls) #tests if the overall distribution conforms to expectations
# testOutliers(so_gls) #tests if there are more simulation outliers than expected
# testDispersion(so_gls) #tests if the simulated dispersion is equal to the observed dispersion
# testQuantiles(so_gls) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
# testZeroInflation(so_gls) #tests if there are more zeros than expected
# 
# summary(m_gls)
```
```{r model-verification-mat-met}
#create df of all metal
mod_met <- site_select %>%
  filter(Material=="Metal") %>% #glass
  group_by(Date, Location, Habitat) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))


m_met  <- glmmTMB(Total ~ #Debris count
                 Habitat + #predicted by Habitat
                 (1|Location) + (1|Date), #site/date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_met)

so_met <- simulateResiduals(fittedModel = m_met, plot=T)
  
plotResiduals(so_met)

testUniformity(so_met) #tests if the overall distribution conforms to expectations
testOutliers(so_met) #tests if there are more simulation outliers than expected
testDispersion(so_met) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_met) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_met) #tests if there are more zeros than expected
```
```{r model-verification-mat-plas}
#create df of all plastic
mod_plas <- site_select %>%
  filter(Material=="Plastic") %>% #glass
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))


m_plas  <- glmmTMB(Total ~ #Debris count
                 Habitat*DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #site/date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_plas)

so_plas <- simulateResiduals(fittedModel = m_plas, plot=T)
  
plotResiduals(so_plas)

testUniformity(so_plas) #tests if the overall distribution conforms to expectations
testOutliers(so_plas) #tests if there are more simulation outliers than expected
testDispersion(so_plas) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_plas) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_plas) #tests if there are more zeros than expected
```
```{r summary-mat}
glmm_met <- summary(m_met)
glmm_met <- as.data.frame(glmm_met$coefficients$cond)
glmm_met <- glmm_met %>%
  mutate(Trait = "Metal")

glmm_plas <- summary(m_plas)
glmm_plas <- as.data.frame(glmm_plas$coefficients$cond)
glmm_plas <- glmm_plas %>%
  mutate(Trait = "Plastic")

glmm_gls <- summary(m_gls)
glmm_gls <- as.data.frame(glmm_gls$coefficients$cond)
glmm_gls <- glmm_gls %>%
  mutate(Trait = "Glass")


glmm_mat <- rbind(glmm_plas, glmm_met, glmm_gls)

write.csv(glmm_mat, "glmm_mat.csv", row.names=T)
```

```{r emmeans-mat}
#plastic
      em_plas_hd <- emmeans(m_plas, pairwise~ Habitat|DistKm , at=list(DistKm=c(1,8)), type="response", level=0.95, infer=T)
      em_plas_dh <- emmeans(m_plas, pairwise~ DistKm|Habitat , at=list(DistKm=c(1,8)), type="response", level=0.95, infer=T)
      
      em_plas1 <- summary(em_plas_hd$contrasts)
      em_plas1$Trait = "Plastic"
      
      em_plas2 <- summary(em_plas_dh$contrasts)
      em_plas2$Trait = "Plastic"
      
#metal
      em_met <- emmeans(m_met, pairwise~Habitat, type="response", level=0.95, infer=T)
      em_met <- summary(em_met$contrasts)
      em_met$Trait = "Metal"
      
#glass
      em_gls_hd <- emmeans(m_gls, pairwise~ Habitat|DistKm , at=list(DistKm=c(1,8)), type="response", level=0.95, infer=T)
      em_gls_dh <- emmeans(m_gls, pairwise~ DistKm|Habitat , at=list(DistKm=c(1,8)), type="response", level=0.95, infer=T)
      
      em_gls1 <- summary(em_gls_hd$contrasts)
      em_gls1$Trait = "Glass"
      
      em_gls2 <- summary(em_gls_dh$contrasts)
      em_gls2$Trait = "Glass"
```

# Fishing classification

```{r drop-levels-fish}
options(scipen = 999)

# Fishing interaction (significant)

     fish_df <- site_select %>%
      filter(Fishing == "Fishing") %>%
      group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
      summarise(Total=sum(Total)) %>%
      ungroup() %>%
      mutate(Location = as.factor(Location),
             Habitat = as.factor(Habitat))
     
     #create model
      m_fish_int <- glmmTMB(Total ~ #Debris count
                     Habitat * DistKm + #predicted by Habitat
                     (1|Location) + (1|Date), #date random effect
                   family=nbinom1(), #negative binomial to deal with count data and zeros
                   data = fish_df)
     
    drop1_fish_int <- drop1(m_fish_int, test="Chisq") #Fishing: Habitat:DistKm  1 257.93 6.6198  0.01008 *
    
    drop1_fish_int <- drop1_fish_int %>%
      filter(LRT != "NA") %>%
      rename(p.value = 'Pr(>Chi)') %>%
      mutate(Fishing = "Fishing", Model="Interaction")

# NonFishing interaction (not significant)

     nonfish_df <- site_select %>%
      filter(Fishing == "Non-Fishing") %>%
      group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
      summarise(Total=sum(Total)) %>%
      ungroup() %>%
      mutate(Location = as.factor(Location),
             Habitat = as.factor(Habitat))
     
     #create model
      m_nonfish_int <- glmmTMB(Total ~ #Debris count
                     Habitat * DistKm + #predicted by Habitat
                     (1|Location) + (1|Date), #date random effect
                   family=nbinom1(), #negative binomial to deal with count data and zeros
                   data = nonfish_df)
     
    drop1_nonfish_int <- drop1(m_nonfish_int, test="Chisq") #Fishing: Habitat:DistKm  1 257.93 6.6198  0.01008 *
    
    drop1_nonfish_int <- drop1_nonfish_int %>%
      filter(LRT != "NA") %>%
      rename(p.value = 'Pr(>Chi)') %>%
      mutate(Fishing = "Non-Fishing", Model="Interaction")
    
# Fishing main effect (Habitat)
     
     #create model
      m_nonfish_main <- glmmTMB(Total ~ #Debris count
                     Habitat + DistKm + #predicted by Habitat
                     (1|Location) + (1|Date), #date random effect
                   family=nbinom1(), #negative binomial to deal with count data and zeros
                   data = nonfish_df)
     
    drop1_nonfish_main <- drop1(m_nonfish_main, test="Chisq") #Fishing: Habitat:DistKm  1 257.93 6.6198  0.01008 *
    
    drop1_nonfish_main <- drop1_nonfish_main %>%
      filter(LRT != "NA") %>%
      rename(p.value = 'Pr(>Chi)') %>%
      mutate(Fishing = "Non-Fishing", Model="Main")

drop1_fishing <- rbind(drop1_nonfish_main, drop1_nonfish_int, drop1_fish_main, drop1_fish_int)
# write.csv(drop1_fishing,"drop1_fishing.csv", row.names = T)
```

```{r model-verification-fishing}
#create df of all plastic
mod_fish <- site_select %>%
  filter(Fishing=="Fishing") %>% #glass
  group_by(Date, Location, Habitat, DistKm) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))


m_fish  <- glmmTMB(Total ~ #Debris count
                 Habitat*DistKm + #predicted by Habitat
                 (1|Location) + (1|Date), #site/date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_fish)

so_fish <- simulateResiduals(fittedModel = m_fish, plot=T)
  
plotResiduals(so_fish)

testUniformity(so_fish) #tests if the overall distribution conforms to expectations
testOutliers(so_fish) #tests if there are more simulation outliers than expected
testDispersion(so_fish) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_fish) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_fish) #tests if there are more zeros than expected
```

```{r model-verification-non-fishing}
#create df of all metal
mod_nonfish <- site_select %>%
  filter(Fishing=="Non-Fishing") %>% 
  group_by(Date, Location, Habitat) %>% #relevant variables
  summarise(Total=sum(Total)) %>%
  ungroup() %>%
  mutate(Location = as.factor(Location),
         Habitat = as.factor(Habitat))


m_nonfish  <- glmmTMB(Total ~ #Debris count
                 Habitat + #predicted by Habitat
                 (1|Location) + (1|Date), #site/date random effect
               family=nbinom1(), #negative binomial to deal with count data and zeros
               data = mod_nonfish)

so_nonfish <- simulateResiduals(fittedModel = m_nonfish, plot=T)
  
plotResiduals(so_nonfish)

testUniformity(so_nonfish) #tests if the overall distribution conforms to expectations
testOutliers(so_nonfish) #tests if there are more simulation outliers than expected
testDispersion(so_nonfish) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_nonfish) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_nonfish) #tests if there are more zeros than expected
```

```{r summary-fish}
glmm_fish <- summary(m_fish)
glmm_fish <- as.data.frame(glmm_fish$coefficients$cond)
glmm_fish <- glmm_fish %>%
  mutate(Trait = "Fishing")

glmm_nonfish <- summary(m_nonfish)
glmm_nonfish <- as.data.frame(glmm_nonfish$coefficients$cond)
glmm_nonfish <- glmm_nonfish %>%
  mutate(Trait = "Non-Fishing")

glmm_fishing <- rbind(glmm_fish, glmm_nonfish)

write.csv(glmm_fishing, "glmm_fishing.csv", row.names=T)
```


```{r emmeans-fish}
# fishing
      em_fish_hd <- emmeans(m_fish, pairwise~ Habitat|DistKm , at=list(DistKm=c(1,8)), type="response", level=0.95, infer=T)
      em_fish_dh <- emmeans(m_fish, pairwise~ DistKm|Habitat , at=list(DistKm=c(1,8)), type="response", level=0.95, infer=T)
      
      em_fish1 <- summary(em_fish_hd$contrasts)
      em_fish1$Trait = "Fishing"
      
      em_fish2 <- summary(em_fish_dh$contrasts)
      em_fish2$Trait = "Fishing"
      
# nonfishing
      em_nonfish <- emmeans(m_nonfish, pairwise~Habitat, type="response", level=0.95, infer=T)
      em_nonfish <- summary(em_nonfish$contrasts)
      em_nonfish$Trait = "Non-Fishing"
```

```{r export-emmeans-tables}
em_hd <- rbind(em_plas1, em_gls1, em_fish1)
em_dh <- rbind(em_gls2, em_plas2, em_fish2)
em_main <- rbind(em_met, em_nonfish)

write.csv(em_hd,"em_hd.csv", row.names = T)
write.csv(em_dh,"em_dh.csv", row.names = T)
write.csv(em_main,"em_main.csv", row.names = T)
```

